import { registerEnumType } from '@nestjs/graphql';

export enum ValidationResponse {
    PENDING = 'PENDING',
    COMPLETE = 'COMPLETE',
    ERROR = 'ERROR',
    IN_PROCESS = 'IN_PROCESS',

    TRANSACTION_PROCESSED = 'TRANSACTION_PROCESSED',
    
    CONTRACT_INCORRECT = 'CONTRACT_INCORRECT',
    CONTRACT_INCOMPLETE = 'CONTRACT_INCOMPLETE',
    CONTRACT_DUPLICATED = 'CONTRACT_DUPLICATED',

    TAXPAYER_SIGEC_INCORRECT = 'TAXPAYER_SIGEC_INCORRECT',
    CONTRACT_SIGEC_ERROR = 'CONTRACT_SIGEC_ERROR',

    //ESTE TIENE QUE DESAPARECER PORQUE DEBERIA NO HACER NADA SI LOS MOVIMIENTOS
    //SON LOS MISMOS Y LOS DATOS DE CONTRATO SON LOS MISMOS, SI ES EL MISMO EGRESO 
    //DEBERIAN ANULARSE LOS YA ENVIADOS Y VOLVERSE A GENERAR SI SON DIFERENTES
    EXIST_MOVEMENTS_SENT = 'EXIST_MOVEMENTS_SENT', 

    MOVEMENT_NOT_EXIST = 'MOVEMENT_NOT_EXIST',
    STAMP_NOT_EXIST = 'STAMP_NOT_EXIST',
}

registerEnumType(ValidationResponse, { name: 'ValidationResponse' });
