export const COL = {
    reversion: 1,
    contractNumber: 2,
    contractValue: 3,
    contractDate: 4,
    contractStartDate: 5,
    contractEndDate: 6,
    movementDate: 7,
    movementValue: 8,
    stampNumber: 9,
    firstName: 10,
    secondName: 11,
    firstLastName: 12,
    secondLastName: 13,
    docNumber: 14,
    docType: 15,
    email: 16,
    phone: 17,
    estado: 18,
    mensaje: 19,
} as const;